### PR TITLE
Use React production build

### PR DESCRIPTION
**Pull request by lotap**
Stops the "It looks like you're using a minified copy of the development build of React." warning on http://frontendhappyhour.com/

### CODE REVIEW

**Comment by augbog** [comment]
Hey thanks for submitting a PR! Sorry about the late response. You mind resolving the conflicts when you get a chance and we can take a look again? It looks like just a few small tidbits and then rebuilding the public files :)

If not, we're also thinking of doing some updates which will include a similar fix.

**Comment by lotap** [comment]
Hi @augbog I can get to this by the end of the week! If you're already working on the updates and are planning to release before that, I can close this.

**Comment by augbog** [comment]
We're also pretty busy 😆  so most likely we won't get to it for a bit. If you do get a chance we'd really appreciate it :) Thanks for contributing!

**Comment by lotap** [comment]
@augbog Oh no! I completely forgot about this until I got a github notification. So sorry! :/ Hope all those updates are coming along nicely

**Pull request closed without merging**
